title: Wings of Fire
author: Anuj Choudhury
email: anuj.choudhury27@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My corner of the internet. Will chiefly use this to add notes, thoughts on various topics, 
  perhaps useful links and more....

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  anujchoudhury # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
