title: My corner of the internet
author: Anuj. 
email: anuj.choudhury27@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Contains my blogs, thoughts, pennings and so on. Sort of my Internet Diary, if you will.
    
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  anujchoudhury # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
